title = "BoldiBest"
copyright = "Palotás Boldizsár"
source = "~/Dropbox/Pictures/ALBUMS/BoldiBest"
target = "/Volumes/BoldiT7Blue/ALBUMS/Web/BoldiBest"

[folders]

[folders.""]
title = "BoldiBest"
reversed = true
